global {
  sparkOptions = {
    "spark.sql.extensions" = "org.apache.sedona.sql.SedonaSqlExtensions,io.delta.sql.DeltaSparkSessionExtension"
    "spark.task.maxFailures" = 1
    "spark.sql.sedona.jts.overlay" = "ng"
    "spark.sql.mapKeyDedupPolicy" = "LAST_WIN"
    "spark.sql.legacy.allowHashOnMapType" = true # legacy setting for HistorizeAction with maps...
  }
  sparkUDFs = {
    udfUuidFromString = {
      className = net.mars.open.pp.utils.UDFUuidFromString
    }
    udfUuidFromLong = {
      className = net.mars.open.pp.utils.UDFUuidFromLong
    }
  }
}

// choose parameters for the country to be processed here
parameters = ${parametersDE}

connections {
  slv-parquet {
    type = HadoopFileConnection
    pathPrefix = "./data/slv"
  }
}

templates {

  slvTable {
    type = ParquetFileDataObject
    connectionId = slv-parquet
  }

}