dataObjects {

  slv-pp = {
    type = DeltaLakeTableDataObject
    table = {
      db = default
      name = slv_pp
    }
    path = "./data/slv/pp"
    saveMode = AppendV2 # avoid bug when appending to Delta Table (https://github.com/delta-io/delta/issues/2564)
    schemaMin = "caseClass#net.mars.open.pp.Pp" # needed because used as recursive input
  }

}