env {
  name = "dev"
  geometriesPath = "s3a://zzeekk-test/mars-open/geometries-ci"
  inputPath = "s3a://zzeekk-test/mars-open/input"
}

global {
  sparkOptions {
    "spark.hadoop.fs.s3a.access.key" = "###ENV#S3_ACCESS_KEY###"
    "spark.hadoop.fs.s3a.secret.key" = "###ENV#S3_ACCESS_KEY###"
  }
}