env {
  name = "dev"
  #catalog = "unity" # set to empty string if no catalog should be used
  dataPath = "./data" # this path should be accessible from unitycatalog and local file system
  inputPath = "./data/ext" # input files are located in the project directory
  geometriesPath = "s3a://zzeekk-test/mars-open/geometries" # geometries are uploaded to S3
  ppPmtilesFilter = true // no filter
}

global {
  sparkOptions {
    "spark.hadoop.fs.s3a.access.key" = "###S3#accessKey###"
    "spark.hadoop.fs.s3a.secret.key" = "###S3#secretKey###"
    #"spark.sql.catalog.unity" = org.apache.spark.sql.delta.catalog.DeltaCatalog
    #"spark.sql.catalog.unity" = io.unitycatalog.spark.UCSingleCatalog
    #"spark.sql.catalog.unity.uri" = "http://localhost:8011"
    #"spark.sql.catalog.uc.token" = not-used
    #"spark.sql.defaultCatalog" = unity
  }

  secretProviders {
    S3 {
      className = io.smartdatalake.util.secrets.FileSecretProvider
      options = {
        file = ${user.home}"/.key/s3"
      }
    }
  }

  environment {
    allowCreateDatabase = true # only on dev, should be false on prod!
  }
}